Repository HUST-SOICT-ICT64/OOLT.ICT.20202.Team3, pull requests merged in 2021-05, with the labels that each got.

#10 Added test for class Column and fix some critcal bugs
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/column/Column.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/test/ColumnTest.java
Labels: bug

#29 Initialize output controller
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/controller/InputController.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/controller/outputcontroller/OutputController.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/column/Column.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/table/IntermediateTable.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/test/ColumnTest.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/view/Output.fxml
Labels: enhancement

#31 update OutputController
  .DS_Store
  QuineMcCluskeyProject/.DS_Store
  QuineMcCluskeyProject/Design/.DS_Store
  QuineMcCluskeyProject/Design/Column package.asta
  QuineMcCluskeyProject/Design/Column package.png
  QuineMcCluskeyProject/Design/General class diagram.asta
  QuineMcCluskeyProject/Design/General class diagram.png
  QuineMcCluskeyProject/Design/Output package.asta
  QuineMcCluskeyProject/Design/Output package.png
  QuineMcCluskeyProject/Design/UseCase Diagram.png
  QuineMcCluskeyProject/Design/controller package.asta
  QuineMcCluskeyProject/Design/controller package.png
  QuineMcCluskeyProject/Design/minterm package.png
  QuineMcCluskeyProject/Design/table package.png
  QuineMcCluskeyProject/src/.DS_Store
  QuineMcCluskeyProject/src/hust/.DS_Store
  QuineMcCluskeyProject/src/hust/soict/.DS_Store
  QuineMcCluskeyProject/src/hust/soict/ict/.DS_Store
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/.DS_Store
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/controller/.DS_Store
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/controller/InputController.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/controller/outputcontroller/.DS_Store
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/controller/outputcontroller/OutputController.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/.DS_Store
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/output/OutputFunction.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/output/POS.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/output/SOP.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/test/OutputFunctionTest.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/view/.DS_Store
Labels: enhancement

#36 Change Table from Interface to Abstract class
  QuineMcCluskeyProject/Design/General class diagram.asta
  QuineMcCluskeyProject/Design/General class diagram.png
  QuineMcCluskeyProject/Design/Table package.asta
  QuineMcCluskeyProject/Design/table package.png
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/table/IntermediateTable.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/table/PITable.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/table/Table.java
Labels: documentation, enhancement

#37 Update GUI for output and Fixing Bug in output
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/controller/outputcontroller/OutputController.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/output/POS.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/output/SOP.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/view/Output.fxml
Labels: bug, enhancement
