Repository HUST-SOICT-ICT64/OOLT.ICT.20202.Team3, pull requests merged in 2021-06, with the labels that each got.

#41 update readme.md
  README.md
Labels: documentation

#42 add class FunctionConverter
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/output/OutputFunction.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/output/POS.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/output/SOP.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/test/OutputFunctionTest.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/utils/FunctionConverter.java
Labels: enhancement

#44 move class Variable to package utils
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/controller/inputcontroller/FourVariablesController.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/controller/inputcontroller/ThreeVariablesController.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/column/Column.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/minterm/Minterm.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/output/POS.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/model/output/SOP.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/test/ColumnTest.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/test/ImplicantTest.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/test/IntermediateTableTest.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/test/OutputFunctionTest.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/test/PrimeImplicantTableTest.java
  QuineMcCluskeyProject/src/hust/soict/ict/quinemccluskey/utils/Variable.java
Labels: enhancement

#47 Feature/report: update report
  report/Final Project OOP Report.docx
Labels: documentation

#48 Feature/report: update the latest version of report and slides
  presentation/Final Project OOP Slides.pptx
  report/Final Project OOP Report.docx
Labels: documentation

#49 update the output package diagram and its following changes
  QuineMcCluskeyProject/Design/.DS_Store
  QuineMcCluskeyProject/Design/General class diagram.asta
  QuineMcCluskeyProject/Design/General class diagram.png
  QuineMcCluskeyProject/Design/Output package.asta
  QuineMcCluskeyProject/Design/Output package.png
  presentation/Final Project OOP Slides.pptx
  presentation/~$Final Project OOP Slides.pptx
  report/Final Project OOP Report.docx
Labels: bug, documentation

#51 update README
  README.md
Labels: documentation
